# Generated by Django 5.0.6 on 2024-07-05 12:14

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=18)),
                ("sub_title", models.CharField(max_length=18)),
                ("image", models.ImageField(upload_to="banner/")),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("image", models.ImageField(upload_to="client_logos/")),
            ],
            options={
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=200)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=200)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField()),
                ("sub_title", models.CharField(max_length=180)),
                ("description", tinymce.models.HTMLField()),
                ("place", models.CharField(max_length=180)),
                ("duration", models.CharField(max_length=180)),
                ("date_time", models.DateTimeField()),
                ("price", models.IntegerField(blank=True, null=True)),
                ("offer_price", models.IntegerField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="event/")),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="Facility/")),
                ("title", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=180)),
                ("answer", models.TextField()),
            ],
            options={
                "verbose_name": "Faq",
                "verbose_name_plural": "Faqs",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gallery_type",
                    models.CharField(
                        choices=[
                            ("image_gallery", "Image Gallery"),
                            ("video_gallery", "Video Gallery"),
                        ],
                        default="image_gallery",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Gallery",
                "verbose_name_plural": "Galleries",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="hotel/")),
                ("price", models.IntegerField()),
                ("per", models.CharField(blank=True, max_length=100, null=True)),
                ("place", models.CharField(blank=True, max_length=100, null=True)),
                ("location_url", models.TextField(blank=True, null=True)),
                ("description", models.TextField()),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "video_cover_image",
                    models.ImageField(blank=True, null=True, upload_to="cover-image/"),
                ),
            ],
            options={
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hotels",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="HotelCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("sub_title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="category/"),
                ),
            ],
            options={
                "verbose_name": "Hotel Category",
                "verbose_name_plural": "Hotel Categories",
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Meta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("about", "About"),
                            ("hotels", "Hotels"),
                            ("image_gallery", "Image Gallery"),
                            ("video_gallery", "Video Gallery"),
                            ("nearby_place", "Nearby Place"),
                            ("updates", "Updates"),
                            ("contact_us", "Contact Us"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("meta_title", models.CharField(max_length=60)),
                ("meta_description", models.CharField(max_length=180)),
                ("url", models.URLField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="meta_image/")),
            ],
            options={
                "verbose_name": "Meta",
                "verbose_name_plural": "Metas",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("position", models.CharField(max_length=180)),
                ("image", models.ImageField(upload_to="team/")),
            ],
            options={
                "verbose_name": "Our Team",
                "verbose_name_plural": "Our Teams",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("content", models.TextField()),
                ("name", models.CharField(max_length=180)),
                ("position", models.CharField(max_length=180)),
                ("image", models.ImageField(upload_to="testimonial/")),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField()),
                ("date", models.DateField(auto_now_add=True)),
                ("auther", models.CharField(max_length=180)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="Update/")),
            ],
            options={
                "verbose_name": "Update",
                "verbose_name_plural": "Updates",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="EventPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Point",
                "verbose_name_plural": "Event Points",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="HotelAmenitiesCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Amenities Category",
                "verbose_name_plural": "Hotel Amenities Categories",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="HotelAmenities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=180)),
                ("title", models.CharField(max_length=180)),
                ("description", models.CharField(max_length=180)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.hotel"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.hotelamenitiescategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="hotel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="web.hotelcategory",
            ),
        ),
        migrations.CreateModel(
            name="HotelEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100)),
                ("check_in", models.CharField(max_length=100)),
                ("check_out", models.CharField(max_length=100)),
                ("adult", models.IntegerField()),
                ("children", models.IntegerField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiries",
                        to="web.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Enquiry",
                "verbose_name_plural": "Hotel Enquiries",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="HotelFaq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=180)),
                ("answer", models.TextField()),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.hotel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Faq ",
                "verbose_name_plural": "Faqs",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="HotelHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.hotel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Highlight ",
                "verbose_name_plural": "Hotel Highlights",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="Hotel-images/")),
                ("title", models.CharField(blank=True, max_length=180, null=True)),
                ("is_space", models.BooleanField(default=False)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.hotel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Image",
                "verbose_name_plural": "Hotel Images",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="HotelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Available", "Available"), ("Booked", "Booked")],
                        default="Available",
                        max_length=20,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotel Availability",
                "verbose_name_plural": "Hotel Availability",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="HotelService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="hotel_service/"
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.hotel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="NearPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("sub_title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="near_place/"),
                ),
                ("place", models.CharField(blank=True, max_length=200, null=True)),
                ("kilometer", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.URLField(blank=True, null=True)),
                ("is_trending", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web.hotelcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Near Place",
                "verbose_name_plural": "Near Places",
                "ordering": ("order",),
            },
        ),
    ]
