# Generated by Django 5.0.6 on 2024-07-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_banner_sub_title_alter_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
