# Generated by Django 5.0.6 on 2024-07-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_delete_hotelservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelamenities',
            name='icon',
        ),
        migrations.AddField(
            model_name='hotelamenities',
            name='image_icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
