# Generated by Django 5.0.6 on 2024-07-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_hotelamenities_icon_hotelamenities_image_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelamenities',
            old_name='image_icon',
            new_name='icon',
        ),
    ]
