# Generated by Django 5.0.6 on 2024-07-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_image_icon_hotelamenities_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelamenities',
            name='description',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='hotelamenities',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
