# Generated by Django 5.0.6 on 2024-07-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_hotelamenities_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelamenities',
            name='icon',
        ),
        migrations.AddField(
            model_name='hotelamenitiescategory',
            name='icon',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
