# Generated by Django 5.0.6 on 2024-07-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_hotelamenities_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelamenities',
            name='description',
        ),
    ]
