# Generated by Django 5.0.6 on 2024-07-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_hotelamenities_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelamenitiescategory',
            name='icon',
            field=models.ImageField(blank=True, max_length=180, null=True, upload_to='icon/'),
        ),
    ]
