# Generated by Django 5.0.6 on 2024-07-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('id',), 'verbose_name': 'Customer Review', 'verbose_name_plural': 'Customer Reviews'},
        ),
    ]
