# Generated by Django 5.0.6 on 2024-07-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_testimonial_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
