# Generated by Django 5.0.6 on 2024-07-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_testimonial_image_alter_testimonial_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.hotel'),
        ),
    ]
