# Generated by Django 5.0.6 on 2024-07-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_testimonial_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
