# Generated by Django 5.0.6 on 2024-07-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_nearplace_offer_price_nearplace_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearplace',
            name='point_1',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='nearplace',
            name='point_2',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
