# Generated by Django 5.0.6 on 2024-07-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_nearplace_point_1_nearplace_point_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearplace',
            name='sub_title',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
